export const ui = {
  'landing.description': 'Send your videos on WhatsApp. Milo, your AI video editor, turns them into a beautiful film.',
  'landing.title': 'Milo — Your video editor on WhatsApp',
  'landing.headline': ['Your moments,', 'beautifully', 'edited.'],
  'landing.cta': 'Start chatting on WhatsApp',
  'landing.chatLabel': 'Example WhatsApp conversation with Milo, an AI video editor',
  'landing.clipDescriptions': ['Wedding flowers and table settings', 'Newlyweds celebrating with their guests', 'Flowers and glasses at the reception', 'The happy couple in the evening light'],
  'landing.sentAlbum': 'You sent four wedding videos',
  'landing.request': 'Our wedding, from everyone’s camera 🥹<br />Can you make us a little recap?',
  'landing.response': 'A little movie of your big day. On it 🤍',
  'landing.result': 'Wedding recap video preview (illustration only)',
  'landing.caption': 'All the love. One little film. ✨',
  'chat.online': 'online',
  'chat.message': 'Message',
  'chat.today': 'Today',
  'chat.verified': 'Verified',
  'chat.read': 'Read',
  'whatsapp.prefill': 'Hi! I have some videos I’d love you to edit.',
  'comparison.before': 'Instead of paying',
  'comparison.after': 'for a video editor,',
  'comparison.headline': 'do it with our AI editor.',
  'comparison.proof': 'More than 1m of video minutes already edited with AI',
  'conversation.label': 'Example WhatsApp conversation with Milo',
  'conversation.scroll': 'Scroll down',
  'conversation.demo': 'Example conversation · Illustrative video previews',
  'conversation.you': 'You',
  'conversation.request': 'Can you please create a video recap and some highlights for our wedding?',
  'conversation.reply': 'Sure, send me your recordings 🤍',
  'conversation.upload': '50 videos sent',
  'conversation.payment': 'Payment verified and accepted ✅',
  'conversation.suggestions': 'Got all 50 videos! Here’s what I suggest editing:',
  'conversation.confirm': 'Shall I create both?',
  'conversation.approval': 'Yes, sounds great! Please create both 🤍',
  'conversation.working': 'Perfect! I’m editing the two videos you approved now ✨',
  'conversation.done': 'Done! Here are the two edited videos you approved 🤍',
  'conversation.recap': 'Wedding recap',
  'conversation.highlights': 'Wedding highlights',
  'conversation.image': 'Wedding moments',
  'closing.heading': 'Turn your moments into an unforgettable film.',
  'footer.rights': 'All rights reserved.',
  'home.choose': 'What would you like to edit?',
};

export type PageContent = typeof ui;
