/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueriesQueryIdRouteImport } from './routes/queries.$queryId'
import { Route as ResultsIndexRouteImport } from './routes/results.index'
import { Route as ResultsResultIdRouteImport } from './routes/results.$resultId'
import { Route as SegmentsSegmentIdRouteImport } from './routes/segments.$segmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueriesQueryIdRoute = QueriesQueryIdRouteImport.update({
  id: '/queries/$queryId',
  path: '/queries/$queryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsResultIdRoute = ResultsResultIdRouteImport.update({
  id: '/results/$resultId',
  path: '/results/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsSegmentIdRoute = SegmentsSegmentIdRouteImport.update({
  id: '/segments/$segmentId',
  path: '/segments/$segmentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/queries/$queryId': typeof QueriesQueryIdRoute
  '/results/$resultId': typeof ResultsResultIdRoute
  '/segments/$segmentId': typeof SegmentsSegmentIdRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/queries/$queryId': typeof QueriesQueryIdRoute
  '/results/$resultId': typeof ResultsResultIdRoute
  '/segments/$segmentId': typeof SegmentsSegmentIdRoute
  '/results': typeof ResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/queries/$queryId': typeof QueriesQueryIdRoute
  '/results/$resultId': typeof ResultsResultIdRoute
  '/segments/$segmentId': typeof SegmentsSegmentIdRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/queries/$queryId'
    | '/results/$resultId'
    | '/segments/$segmentId'
    | '/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/queries/$queryId'
    | '/results/$resultId'
    | '/segments/$segmentId'
    | '/results'
  id:
    | '__root__'
    | '/'
    | '/queries/$queryId'
    | '/results/$resultId'
    | '/segments/$segmentId'
    | '/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QueriesQueryIdRoute: typeof QueriesQueryIdRoute
  ResultsResultIdRoute: typeof ResultsResultIdRoute
  SegmentsSegmentIdRoute: typeof SegmentsSegmentIdRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queries/$queryId': {
      id: '/queries/$queryId'
      path: '/queries/$queryId'
      fullPath: '/queries/$queryId'
      preLoaderRoute: typeof QueriesQueryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$resultId': {
      id: '/results/$resultId'
      path: '/results/$resultId'
      fullPath: '/results/$resultId'
      preLoaderRoute: typeof ResultsResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments/$segmentId': {
      id: '/segments/$segmentId'
      path: '/segments/$segmentId'
      fullPath: '/segments/$segmentId'
      preLoaderRoute: typeof SegmentsSegmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QueriesQueryIdRoute: QueriesQueryIdRoute,
  ResultsResultIdRoute: ResultsResultIdRoute,
  SegmentsSegmentIdRoute: SegmentsSegmentIdRoute,
  ResultsIndexRoute: ResultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
